name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get yarn global directory path
        id: yarn-cache-global-path
        run: echo "::set-output name=dir::$(yarn global dir)"

      - name: Build cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-global-path.outputs.dir }}
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-www-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-www-

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: out
          clean: true
          single-commit: true
